### ISSUE TITLE
Individual cards

### ISSUE THREAD

**Issue by prolink007** [Tyrox1/Keyforge-Downloader#1]
Have you figured out a way to look up individual cards using their API? I am unable to find a path for it.

I know a way to brute force every individual card, but just wondering if you had found a path while writing this script.

Thanks

**Comment by Tyrox1** [comment]
Hi @prolink007 ,

sorry for the extremely long response time, I forgot to setup Email nofications for this account and didn't look here.
So far I have not found a solution for individual cards, sorry to dissapoint.
